import g923Logo from '@/assets/G923_trueforce_logo.webp'
import LoLKda from '@/assets/LoL_G_Kda_lockup.webp'
import img3 from '@/assets/Logitech_Aurora_Collection.jpg'
import img2 from '@/assets/Logitech_G_G502.png'
import img5 from '@/assets/Logitech_G_Pro_X_wireless.png'
import img1 from '@/assets/Logitech_G_Vantum.jpeg'
import img4 from '@/assets/Logitech_LoL.png'
import video2 from '@/assets/videos/Logitech_G_923.mp4'
import video1 from '@/assets/videos/Logitech_G_Fits.mp4'
import video3 from '@/assets/videos/Logitech_G_LoL_KDA.mp4'

export const mediaList = [
	{
		id: 1,
		media: img1,
		logo: null,
		title: 'Divulgue o seu jogo',
		subTitle: null,
		description: null,
		button: 'conheça o vantum',
		details: false,
		classes: {
			containerClass: 'container-1',
			logoClass: '',
			titleClass: 'title-1',
			subtitleClass: '',
			descriptionClass: '',
			buttonClass: 'button-1',
		},
	},
	{
		id: 2,
		media: video1,
		logo: null,
		title: `Ajuste perfecto para la\ndiversión`,
		subTitle: null,
		description: 'Audífonos inalámbricos para juegos que se amoldan para ajustarse a tus oídos',
		button: 'Presentamos Fits',
		details: false,
		classes: {
			containerClass: 'container-2',
			logoClass: '',
			titleClass: 'title-2',
			subtitleClass: '',
			descriptionClass: 'description-2',
			buttonClass: 'button-2',
		},
	},
	{
		id: 3,
		media: img2,
		logo: null,
		title: 'Un icono. renovado.',
		subTitle: null,
		description: `La gama G502 X.\nEl diseño del legendario G502 renovado\ncon tecnología para juegos pionera.`,
		button: 'Presentamos la gama G502 X',
		details: false,
		classes: {
			containerClass: 'container-3',
			logoClass: '',
			titleClass: 'title-3',
			subtitleClass: '',
			descriptionClass: 'description-3',
			buttonClass: 'button-3',
		},
	},
	{
		id: 4,
		media: img3,
		logo: null,
		title: 'Juega a tu manera',
		subTitle: 'Presentamos The Aurora Collection',
		description: null,
		button: 'Descúbrela y personaliza a tu gusto',
		details: false,
		classes: {
			containerClass: 'container-4',
			logoClass: '',
			titleClass: 'title-4',
			subtitleClass: 'subtitle-4',
			descriptionClass: '',
			buttonClass: 'button-4',
		},
	},
	{
		id: 5,
		media: img4,
		logo: null,
		title: 'Juega con legends',
		subTitle: null,
		description:
			'Creada por arte de magia. Perfeccionada por la ciencia. Utilizada por\ncampeones. Presentamos la Colección League of Legends.',
		button: 'Explorar colecciones League of Legends',
		details: false,
		classes: {
			containerClass: 'container-5',
			logoClass: '',
			titleClass: 'title-5',
			subtitleClass: '',
			descriptionClass: 'description-5',
			buttonClass: 'button-5',
		},
	},
	{
		id: 6,
		media: img5,
		logo: null,
		title: 'Pro con Lightspeed',
		subTitle: 'Pro X\ninalámbricos',
		description: null,
		button: 'Más sobre inalámbricos Pro',
		details: true,
		classes: {
			containerClass: 'container-6',
			logoClass: '',
			titleClass: 'title-6',
			subtitleClass: 'subtitle-6',
			descriptionClass: '',
			buttonClass: 'button-6',
		},
	},
	{
		id: 7,
		media: video2,
		logo: g923Logo,
		title: 'Force feedback de próxima generación',
		subTitle: null,
		description: null,
		button: 'Presentamos G923',
		details: false,
		classes: {
			containerClass: 'container-7',
			logoClass: 'logo-7',
			titleClass: 'title-7',
			subtitleClass: '',
			descriptionClass: '',
			buttonClass: 'button-7',
		},
	},
	{
		id: 8,
		media: video3,
		logo: LoLKda,
		title: 'Juega al tope',
		subTitle: null,
		description: null,
		button: 'Explora dispositivos y accesorios K/DA ahora',
		details: false,
		classes: {
			containerClass: 'container-8',
			logoClass: 'logo-8',
			titleClass: 'title-8',
			subtitleClass: '',
			descriptionClass: '',
			buttonClass: 'button-8',
		},
	},
]
